- name: TestPutOperation
  operation_type: put
  connection_config: ""
  source_file: ""
  database: demo_db
  schema: public

- name: TestPutOperation2
  operation_type: put
  connection_config: ""
  source_file: ""
  database: demo_db
  schema: public
