- name: TestPutOperation
  operation_type: put
  template_file: /media/ajkdrag/Overdrive/vs_workspace/projects/SnowflakeDataPorter/src/templates/put.template.yaml
  connection_config: /media/ajkdrag/Overdrive/vs_workspace/projects/SnowflakeDataPorter/src/configs/snowflake_conn.cfg.yaml
  source: /media/ajkdrag/Overdrive/vs_workspace/projects/SnowflakeDataPorter/.files/test_file_1.csv
  stage_type: user
  target: "test"
  database: demo_db
  schema: public

- name: TestPutOperation2
  operation_type: put
  template_file: /media/ajkdrag/Overdrive/vs_workspace/projects/SnowflakeDataPorter/src/templates/put.template.yaml
  connection_config: /media/ajkdrag/Overdrive/vs_workspace/projects/SnowflakeDataPorter/src/configs/snowflake_conn.cfg.yaml
  source: /media/ajkdrag/Overdrive/vs_workspace/projects/SnowflakeDataPorter/.files/test_file_2.csv
  stage_type: table
  target: test
  database: demo_db
  schema: public

- name: TestGetOperation
  operation_type: get
  template_file: /media/ajkdrag/Overdrive/vs_workspace/projects/SnowflakeDataPorter/src/templates/get.template.yaml
  connection_config: /media/ajkdrag/Overdrive/vs_workspace/projects/SnowflakeDataPorter/src/configs/snowflake_conn.cfg.yaml
  source: test
  stage_type: user
  target: /media/ajkdrag/Overdrive/vs_workspace/projects/SnowflakeDataPorter/.files/get/
  database: demo_db
  schema: public

- name: TestGetOperation2
  operation_type: get
  template_file: /media/ajkdrag/Overdrive/vs_workspace/projects/SnowflakeDataPorter/src/templates/get.template.yaml
  connection_config: /media/ajkdrag/Overdrive/vs_workspace/projects/SnowflakeDataPorter/src/configs/snowflake_conn.cfg.yaml
  source: test
  stage_type: table
  target: /media/ajkdrag/Overdrive/vs_workspace/projects/SnowflakeDataPorter/.files/get/
  database: demo_db
  schema: public